server:
  port: 8848
  servlet:
    context-path: /yml

student:
  name: "somebody"                           # 字符串
  age: 12                                 # 数值
  gender: '女'                            # 字符串
  married: false                         # 布尔
  birthday: 2020/12/12 12:12:12           # Date
  info: 你猜我服了吗                         # 字符串
  hobby: ["唱", "跳", "rap", "篮球"]        # 数组
  food:                                   # 集合
    - 麻辣小龙虾
    - 可乐鸡翅
    - 披萨
    - 火锅
    - barbeque
  score: {"high": 160, "weight": 90, "eye": 2}    # Map
  car:                                       # 对象
    brand: byd
    color: white
  person:
    name: zch
